import type { AppState, Member, OwnerAccount, Property, User } from "./types";

export const users: User[] = [
  {
    id: "user_tanaka",
    name: "田中 美咲",
    role: "company",
    companyId: "sunrise",
    companyName: "サンライズ管理株式会社",
    title: "物件担当",
  },
  {
    id: "user_suzuki",
    name: "鈴木 健一",
    role: "company",
    companyId: "minato",
    companyName: "港区アセットマネジメント",
    title: "リーシング責任者",
  },
  {
    id: "user_izumi",
    name: "泉 担当",
    role: "admin",
    title: "運営（物件供給・最終確認）",
  },
];

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const members: Member[] = [
  { id: "m1", displayName: "佐藤 悠真", lineId: "u_sato", initial: "佐", hue: 198, registeredAt: hoursAgo(720), source: "泉氏・既存顧客" },
  { id: "m2", displayName: "高橋 莉子", lineId: "u_takahashi", initial: "高", hue: 172, registeredAt: hoursAgo(680), source: "泉氏・既存顧客" },
  { id: "m3", displayName: "伊藤 蓮", lineId: "u_ito", initial: "伊", hue: 210, registeredAt: hoursAgo(640), source: "泉氏・既存顧客" },
  { id: "m4", displayName: "渡辺 彩花", lineId: "u_watanabe", initial: "渡", hue: 186, registeredAt: hoursAgo(600), source: "泉氏・既存顧客" },
  { id: "m5", displayName: "山本 大輝", lineId: "u_yamamoto", initial: "山", hue: 164, registeredAt: hoursAgo(520), source: "紹介" },
  { id: "m6", displayName: "中村 咲", lineId: "u_nakamura", initial: "中", hue: 204, registeredAt: hoursAgo(480), source: "泉氏・既存顧客" },
  { id: "m7", displayName: "小林 隼人", lineId: "u_kobayashi", initial: "小", hue: 190, registeredAt: hoursAgo(400), source: "泉氏・既存顧客" },
  { id: "m8", displayName: "加藤 美月", lineId: "u_kato", initial: "加", hue: 176, registeredAt: hoursAgo(320), source: "紹介" },
  { id: "m9", displayName: "吉田 陽菜", lineId: "u_yoshida", initial: "吉", hue: 200, registeredAt: hoursAgo(240), source: "泉氏・既存顧客" },
  { id: "m10", displayName: "山田 拓海", lineId: "u_yamada", initial: "山", hue: 158, registeredAt: hoursAgo(180), source: "泉氏・既存顧客" },
  { id: "m11", displayName: "佐々木 結衣", lineId: "u_sasaki", initial: "佐", hue: 214, registeredAt: hoursAgo(96), source: "泉氏・既存顧客" },
  { id: "m12", displayName: "松本 悠", lineId: "u_matsumoto", initial: "松", hue: 182, registeredAt: hoursAgo(36), source: "新規登録" },
];

const images = {
  shirokane: [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
  ],
  sakura: [
    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80",
  ],
  hamamatsu: [
    "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
  ],
  shinagawa: [
    "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
  ],
};

export const properties: Property[] = [
  {
    id: "p_shirokane",
    companyId: "sunrise",
    companyName: "サンライズ管理株式会社",
    status: "submitted",
    name: "パークホームズ白金台 3LDK",
    buildingName: "パークホームズ白金台",
    prefecture: "東京都",
    city: "港区",
    town: "白金台",
    addressDetail: "4-12-8",
    roomNumber: "1203",
    floor: 12,
    totalFloors: 14,
    layout: "3LDK",
    area: 82.4,
    balconyArea: 12.1,
    builtYear: 2016,
    builtMonth: 3,
    direction: "南",
    station: "白金台駅",
    walkMinutes: 6,
    price: 8980,
    managementFee: 24800,
    reserveFund: 18600,
    highlights: [
      "白金台駅徒歩6分・閑静な住宅街",
      "南向き・陽当たり良好",
      "ペット飼育可（細則あり）",
      "SUUMO掲載前の未公開物件",
    ],
    notes: "オーナーは早期売却希望。資料作成中のため一般公開は来週予定。",
    images: images.shirokane,
    pdfName: "パークホームズ白金台_概要.pdf",
    petAllowed: true,
    maskedFields: ["addressDetail", "roomNumber"],
    broadcastFormat: "bullets",
    customMessage: "",
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(6),
    submittedAt: hoursAgo(6),
  },
  {
    id: "p_sakura",
    companyId: "sunrise",
    companyName: "サンライズ管理株式会社",
    status: "broadcasted",
    name: "ザ・パークハウス桜新町 2LDK",
    buildingName: "ザ・パークハウス桜新町",
    prefecture: "東京都",
    city: "世田谷区",
    town: "桜新町",
    addressDetail: "2-8-15",
    roomNumber: "503",
    floor: 5,
    totalFloors: 8,
    layout: "2LDK",
    area: 65.8,
    balconyArea: 8.4,
    builtYear: 2012,
    builtMonth: 11,
    direction: "南東",
    station: "桜新町駅",
    walkMinutes: 5,
    price: 6480,
    managementFee: 18600,
    reserveFund: 14200,
    highlights: [
      "桜新町駅徒歩5分",
      "リノベーション済み室内",
      "ファミリー層に人気の学区",
    ],
    notes: "価格の反応テストも兼ねて配信済み。",
    images: images.sakura,
    pdfName: "ザ・パークハウス桜新町_概要.pdf",
    petAllowed: false,
    maskedFields: ["addressDetail", "roomNumber", "price"],
    broadcastFormat: "card",
    customMessage: "価格は非公開です。気になる方はスタンプでお知らせください。",
    createdAt: hoursAgo(80),
    updatedAt: hoursAgo(20),
    submittedAt: hoursAgo(28),
    reviewedAt: hoursAgo(22),
    broadcastedAt: hoursAgo(20),
  },
  {
    id: "p_hamamatsu",
    companyId: "sunrise",
    companyName: "サンライズ管理株式会社",
    status: "draft",
    name: "ブリリアタワー浜松町 1LDK",
    buildingName: "ブリリアタワー浜松町",
    prefecture: "東京都",
    city: "港区",
    town: "浜松町",
    addressDetail: "1-9-3",
    roomNumber: "2807",
    floor: 28,
    totalFloors: 33,
    layout: "1LDK",
    area: 48.2,
    balconyArea: 6.8,
    builtYear: 2020,
    builtMonth: 2,
    direction: "西",
    station: "浜松町駅",
    walkMinutes: 4,
    price: 7280,
    managementFee: 22100,
    reserveFund: 16800,
    highlights: ["浜松町駅徒歩4分", "高層階・夜景良好", "ホテルライクな共用部"],
    notes: "入力途中。オーナー確認後に送信予定。",
    images: images.hamamatsu,
    petAllowed: false,
    maskedFields: ["addressDetail", "roomNumber"],
    broadcastFormat: "bullets",
    customMessage: "",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(2),
  },
  {
    id: "p_shinagawa",
    companyId: "minato",
    companyName: "港区アセットマネジメント",
    status: "submitted",
    name: "シティタワー品川 3LDK",
    buildingName: "シティタワー品川",
    prefecture: "東京都",
    city: "港区",
    town: "港南",
    addressDetail: "3-6-21",
    roomNumber: "1902",
    floor: 19,
    totalFloors: 36,
    layout: "3LDK",
    area: 88.9,
    balconyArea: 14.6,
    builtYear: 2008,
    builtMonth: 7,
    direction: "東",
    station: "品川駅",
    walkMinutes: 8,
    price: 11800,
    managementFee: 31200,
    reserveFund: 24600,
    highlights: [
      "品川駅徒歩圏のタワーマンション",
      "3LDK・ファミリー向け",
      "共用施設が充実",
    ],
    notes: "来週SUUMO申請予定。未公開期間に先出ししたい。",
    images: images.shinagawa,
    pdfName: "シティタワー品川_概要.pdf",
    petAllowed: true,
    maskedFields: ["addressDetail", "roomNumber"],
    broadcastFormat: "pdf",
    customMessage: "",
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(4),
    submittedAt: hoursAgo(4),
  },
];

export const owners: OwnerAccount[] = [
  {
    id: "o_saito",
    name: "斎藤 真理",
    email: "saito@sunrise-kanri.example",
    affiliation: "サンライズ管理株式会社",
    status: "active",
    propertyIds: ["p_sakura", "p_hamamatsu"],
    createdAt: hoursAgo(240),
  },
  {
    id: "o_kondo",
    name: "近藤 隼",
    email: "kondo@minato-am.example",
    affiliation: "港区アセットマネジメント",
    status: "invited",
    propertyIds: ["p_shinagawa"],
    createdAt: hoursAgo(36),
  },
  {
    id: "o_mori",
    name: "森 恵",
    email: "mori@sunrise-kanri.example",
    affiliation: "サンライズ管理株式会社",
    status: "suspended",
    propertyIds: ["p_shirokane"],
    createdAt: hoursAgo(400),
  },
];

export const initialState: AppState = {
  currentUser: null,
  properties,
  members,
  owners,
  broadcasts: [
    {
      id: "b_sakura",
      propertyId: "p_sakura",
      sentAt: hoursAgo(20),
      format: "card",
      recipientCount: 248,
      messageText:
        "【未公開マンション情報】\n\nザ・パークハウス桜新町\n所在地：東京都世田谷区桜新町（詳細非公開）\n間取り：2LDK ／ 65.8㎡",
    },
  ],
  reactions: [
    { id: "r1", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m2", type: "like", createdAt: hoursAgo(19) },
    { id: "r2", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m4", type: "stamp", stamp: "🏠", createdAt: hoursAgo(18.4) },
    { id: "r3", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m7", type: "like", createdAt: hoursAgo(17) },
    { id: "r4", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m9", type: "text", message: "内見できますか？", createdAt: hoursAgo(12) },
    { id: "r5", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m11", type: "stamp", stamp: "👍", createdAt: hoursAgo(8) },
    { id: "r6", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m1", type: "like", createdAt: hoursAgo(72) },
    { id: "r7", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m3", type: "text", message: "資料をください", createdAt: hoursAgo(96) },
    { id: "r8", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m5", type: "stamp", stamp: "🏠", createdAt: hoursAgo(120) },
    { id: "r9", broadcastId: "b_sakura", propertyId: "p_sakura", memberId: "m6", type: "like", createdAt: hoursAgo(144) },
  ],
};

export const presetImages = [
  images.shirokane[0],
  images.sakura[0],
  images.hamamatsu[0],
  images.shinagawa[0],
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
  "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1600&q=80",
];
